FROM docker.m.daocloud.io/library/python:3.12-slim

WORKDIR /app
COPY pmo-api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r /app/requirements.txt
COPY pmo-api/ /app/

EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
