name: yu-project-management-yu-pmo-v1

services:
  wekan:
    image: yu-project-management:local
    build:
      context: .
      dockerfile: Dockerfile.yu-cn
    ports: !override
      - "3000:8080"
    environment:
      ROOT_URL: http://localhost:3000
      MAIL_URL: ""
      MAIL_FROM: ""
      MAIL_SERVICE: ""
      MAIL_SERVICE_USER: ""
      MAIL_SERVICE_PASSWORD: ""

  ferretdb:
    image: docker.m.daocloud.io/library/debian:bookworm-slim
    ports: !override
      - "127.0.0.1:27017:27017"
